global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'capibara-core'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 5s

  - job_name: 'capibara-health'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: '/health'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Add more targets as needed
  # - job_name: 'capibara-cluster'
  #   static_configs:
  #     - targets: ['capibara-1:8080', 'capibara-2:8080', 'capibara-3:8080']
